name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Maven Release and Publish
        uses: qcastel/github-actions-maven-release@master
        with:
          version-minor: true
          maven-repo-server-id: github
          maven-repo-server-username: ${{ secrets.GH_USERNAME }}
          maven-repo-server-password: ${{ secrets.GH_TOKEN }}
          git-release-bot-name: ${{ secrets.GH_USERNAME }}
          git-release-bot-email: "actions@github.com"
          # Github access token. https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
          access-token: ${{ secrets.GH_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          maven-release-publish: true
          gpg-enabled: false
          maven-snapshot-publish: "false"
