name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Maven Release and Publish
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          version-minor: true
          maven-repo-server-id: github
          maven-repo-server-username: ${{ secrets.GH_USERNAME }}
          maven-repo-server-password: ${{ secrets.GH_TOKEN }}
          git-release-bot-name: ${{ secrets.GH_USERNAME }}
          git-release-bot-email: "actions@github.com"
          gpg-enabled: false
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
